name: Update issue Status

on:
  issues:
    types: [closed]

jobs:
  update_issue:
    uses: specklesystems/github-actions/.github/workflows/project-update-issue-status.yml@main
    secrets: inherit
    with:
      issue-id: ${{ github.event.issue.node_id }}
